accumulate_grad_batches: 1
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 256
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
dataset_config: conf/dataset/nsmc.json
default_root_dir: null
deterministic: false
distributed_backend: null
early_stop_callback: false
embedding_dim: 32
epochs: 5
fast_dev_run: false
fix_seed: false
gradient_clip_val: 0
learning_rate: 0.001
length: 300
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_gpu_memory: null
log_save_interval: 100
logger: true
max_epochs: 1000
max_steps: null
min_epochs: 1
min_steps: null
model_config: conf/model/charcnn.json
num_classes: 2
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
overfit_pct: null
precision: 32
prepare_data_per_node: true
print_nan_grads: false
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 50
summary_step: 500
terminate_on_nan: false
test: nsmc/test.txt
test_percent_check: null
track_grad_norm: -1
train: nsmc/train.txt
train_percent_check: null
truncated_bptt_steps: null
type: charcnn
val_check_interval: 1.0
val_percent_check: null
validation: nsmc/validation.txt
vocab: nsmc/vocab.pkl
weights_save_path: null
weights_summary: top
